org: jaseem97
app: imap
service: demo
package:
  artifact: 'target/emailRetriever-0.0.1-SNAPSHOT.jar'
provider:
  name: aws
functions:
  loginAndFetchAllMails:
    handler: com.example.pieEye.emailRetriever.ServerlessHandler.LoginHandler
    events:
      - http:
          path: /mails
          method: post
  fetchOneMail:
    handler: com.example.pieEye.emailRetriever.ServerlessHandler.FetchMailHandler
    events:
      - http:
          path: /mails/{id}
          method: get
  logout:
    handler: com.example.pieEye.emailRetriever.ServerlessHandler.LogoutHandler
    events:
      - http:
          path: /mails/logout
          method: get


